dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
  apt:
    packages:
      - dpkg

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test_headless
  - npm run e2e_headless
